const superagent = require("superagent");
const EM = require("evomaster-client-js").EMTestUtils;
jest.setTimeout(60000);




/**
 * This file was automatically generated by EvoMaster on 2024-04-24T11:09:29.929-03:00[America/Argentina/Buenos_Aires]
 * 
 * The generated test suite contains 2 tests
 * 
 * Covered targets: 4
 * 
 * Used time: 0h 1m 58s
 * 
 * Needed budget for current results: 72%
 * 
 * This file contains test cases that represent failed calls, but not indicative of faults.
 */

const baseUrlOfSut = "http://localhost:5001";


beforeAll( async () => {
});








test("test_0", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/remainder/967/-1120529324").set('Accept', "application/json")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.text).toBe("\"\"");
});


test("test_1", async () => {
    
    const res_0 = await superagent
            .get(baseUrlOfSut + "/api/bessj/2059764225/0.15354801279535624").set('Accept', "application/json")
            .ok(res => res.status);
    
    expect(res_0.status).toBe(400);
    expect(res_0.header["content-type"].startsWith("application/json")).toBe(true);
    expect(res_0.text).toBe("\"\"");
});
