package generated_go_5m

import (
    "github.com/stretchr/testify/suite"
    "github.com/valyala/fastjson"
    "io"
    "net/http"
    "strings"
    "testing"
)

// These vars are added so Go compiler doesn't complain if imports aren't used
var _ *fastjson.Object = nil
var _ *io.Reader = nil
var _ *strings.Reader = nil




/**
 * This file was automatically generated by EvoMaster on 2024-04-12T16:43:02.756-03:00[America/Argentina/Buenos_Aires]
 * 
 * The generated test suite contains 2 tests
 * 
 * Covered targets: 5
 * 
 * Used time: 0h 5m 0s
 * 
 * Needed budget for current results: 41%
 * 
 * This file contains one example of each category of fault. The test cases in this file are a subset of the set of test cases likely to indicate faults.
 */
type EvoMasterFaultRepresentativesTest struct {
    suite.Suite
    Controller *AppController
    BaseUrlOfSut string
}

func TestEvoMasterFaultRepresentativesSuite(t *testing.T) {
    suite.Run(t, new(EvoMasterFaultRepresentativesTest))
}


func (suite *EvoMasterFaultRepresentativesTest) SetupSuite() {
    suite.Controller = &AppController{}
    suite.Controller.SetPort(5012)
    suite.BaseUrlOfSut = suite.Controller.StartSut()
}


func (suite *EvoMasterFaultRepresentativesTest) TearDownSuite() {
    suite.Controller.StopSut()
}


func (suite *EvoMasterFaultRepresentativesTest) SetupTest() {
    suite.Controller.ResetStateOfSUT()
}




/**
* [Test_0_with500] is a part of 1 or more clusters, as defined by the selected clustering options. 
* LastLine_0
*/
func (suite *EvoMasterFaultRepresentativesTest) Test_0_with500() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/fisher/890/-179/8.988465674311579E307?EMextraParam123=_EM_0_XYZ_"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    req.Header.Set("x-EMextraHeader123", "_EM_1_XYZ_")
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
    
    suite.Equal(500, res_0.StatusCode) // github.com/jcbasso/EMB/go/rest/artificial/ncs/src:utils.go_19_61
    suite.Equal(http.NoBody, res_0.Body)
}


func (suite *EvoMasterFaultRepresentativesTest) Test_1() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/fisher/16794/333/0.96776"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    req.Header.Set("x-EMextraHeader123", "")
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
    
    suite.Equal(400, res_0.StatusCode)
    suite.True(strings.HasPrefix(res_0.Header.Get("Content-Type"), "application/json"))
    body_1, err := io.ReadAll(res_0.Body)
    suite.NoError(err, "Request body read error must be nil")
    
    var p fastjson.Parser
    v_body_1, err := p.ParseBytes(body_1)
    suite.NoError(err, "Parser body creation error must be nil")
    suite.Contains(string(v_body_1.GetStringBytes()), "")
}
