package generated_go_30s

import (
	"github.com/stretchr/testify/suite"
	"github.com/valyala/fastjson"
	"io"
	"net/http"
	"strings"
	"testing"
)

// These vars are added so Go compiler doesn't complain if imports aren't used
var _ *fastjson.Object = nil
var _ *io.Reader = nil
var _ *strings.Reader = nil
var _ *fastjson.Object = nil

/**
 * This file was automatically generated by EvoMaster on 2024-03-13T11:49:41.413-03:00[America/Argentina/Buenos_Aires]
 *
 * The generated test suite contains 1 tests
 *
 * Covered targets: 4
 *
 * Used time: 0h 0m 30s
 *
 * Needed budget for current results: 100%
 *
 * This file contains one example of each category of fault. The test cases in this file are a subset of the set of test cases likely to indicate faults.
 */
type EvoMasterFaultRepresentativesTest struct {
	suite.Suite
	Controller   *AppController
	BaseUrlOfSut string
}

func TestEvoMasterFaultRepresentativesSuite(t *testing.T) {
	suite.Run(t, new(EvoMasterFaultRepresentativesTest))
}

func (suite *EvoMasterFaultRepresentativesTest) SetupSuite() {
	suite.Controller = &AppController{}
	suite.Controller.SetPort(5012)
	suite.BaseUrlOfSut = suite.Controller.StartSut()
}

func (suite *EvoMasterFaultRepresentativesTest) TearDownSuite() {
	suite.Controller.StopSut()
}

func (suite *EvoMasterFaultRepresentativesTest) SetupTest() {
	suite.Controller.ResetStateOfSUT()
}

func (suite *EvoMasterFaultRepresentativesTest) Test_0_with500() {

	method := http.MethodGet
	reqUrl := "http://" + suite.BaseUrlOfSut + "/api/fisher/-1047772/362/-6821493.5436412?EMextraParam123=_EM_83_XYZ_"

	req, err := http.NewRequest(method, reqUrl, nil)
	suite.Nil(err, "Request creation error must be nil")

	req.Header.Set("x-EMextraHeader123", "_EM_84_XYZ_")
	res_0, err := http.DefaultClient.Do(req)
	suite.NoError(err, "Request error must be nil")
	defer res_0.Body.Close()

	suite.Equal(500, res_0.StatusCode) //
	suite.Equal(http.NoBody, res_0.Body)
}
