package generated_bb_go_1m

import (
    "github.com/stretchr/testify/suite"
    "github.com/valyala/fastjson"
    "io"
    "net/http"
    "strings"
    "testing"
)

// These vars are added so Go compiler doesn't complain if imports aren't used
var _ *fastjson.Object = nil
var _ *io.Reader = nil
var _ *strings.Reader = nil




/**
 * This file was automatically generated by EvoMaster on 2024-04-24T14:49:24.530-03:00[America/Argentina/Buenos_Aires]
 * 
 * The generated test suite contains 9 tests
 * 
 * Covered targets: 19
 * 
 * Used time: 0h 1m 58s
 * 
 * Needed budget for current results: 72%
 * 
 * This file contains one example of each category of fault. The test cases in this file are a subset of the set of test cases likely to indicate faults.
 */
type EvoMasterFaultRepresentativesTest struct {
    suite.Suite
    BaseUrlOfSut string
}

func TestEvoMasterFaultRepresentativesSuite(t *testing.T) {
    suite.Run(t, new(EvoMasterFaultRepresentativesTest))
}


func (suite *EvoMasterFaultRepresentativesTest) SetupSuite() {
    suite.BaseUrlOfSut = "localhost:5001"
}








func (suite *EvoMasterFaultRepresentativesTest) Test_0() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/expint/522/0.31531501628136305"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
}


func (suite *EvoMasterFaultRepresentativesTest) Test_1() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/remainder/880/678"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
}


func (suite *EvoMasterFaultRepresentativesTest) Test_2() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/triangle/379/713/762"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
}


func (suite *EvoMasterFaultRepresentativesTest) Test_3() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/fisher/801/519/0.5267259880752357"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
}


func (suite *EvoMasterFaultRepresentativesTest) Test_4() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/bessj/445/0.8296912233491993"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
}


func (suite *EvoMasterFaultRepresentativesTest) Test_5() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/gammq/0.5722295925058892/0.5559666311129164"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
}


func (suite *EvoMasterFaultRepresentativesTest) Test_6() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/swagger.json"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
    
    suite.Equal(200, res_0.StatusCode)
}


func (suite *EvoMasterFaultRepresentativesTest) Test_7() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/remainder/967/-1120529324"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
    
    suite.Equal(400, res_0.StatusCode)
    suite.True(strings.HasPrefix(res_0.Header.Get("Content-Type"), "application/json"))
    body_1, err := io.ReadAll(res_0.Body)
    suite.NoError(err, "Request body read error must be nil")
    
    var p fastjson.Parser
    v_body_1, err := p.ParseBytes(body_1)
    suite.NoError(err, "Parser body creation error must be nil")
    suite.Contains(string(v_body_1.GetStringBytes()), "")
}


func (suite *EvoMasterFaultRepresentativesTest) Test_8() {
    
    
    method := http.MethodGet
    reqUrl := "http://" + suite.BaseUrlOfSut + "/api/bessj/2059764225/0.15354801279535624"
    
    req, err := http.NewRequest(method, reqUrl, nil)
    suite.Nil(err, "Request creation error must be nil")
    
    res_0, err := http.DefaultClient.Do(req)
    suite.NoError(err, "Request error must be nil")
    defer res_0.Body.Close()
    
    suite.Equal(400, res_0.StatusCode)
    suite.True(strings.HasPrefix(res_0.Header.Get("Content-Type"), "application/json"))
    body_1, err := io.ReadAll(res_0.Body)
    suite.NoError(err, "Request body read error must be nil")
    
    var p fastjson.Parser
    v_body_1, err := p.ParseBytes(body_1)
    suite.NoError(err, "Parser body creation error must be nil")
    suite.Contains(string(v_body_1.GetStringBytes()), "")
}
